### ISSUE TITLE
Hello Professor, my code seem not to be recognizing the "SparseObjectMatrix" class. I am unable to identify the problem.

### ISSUE THREAD

**Issue by onyemakn** [ddobric/neocortexapi#41]
https://github.com/onyemakn/neocortexapi/blob/KizitoOnyema_NeocortexApi/source/HtmPersistence/Program.cs

![Screenshot (172)](https://user-images.githubusercontent.com/9866193/151190487-6b32b621-7411-48cb-8df8-8311e5968034.png)

**Comment by Noath2302** [comment]
Hi there, 
It seems that your project which calls the code didn't add reference to other projects.
Your calls in line 1 created an error

**Comment by onyemakn** [comment]
Hi Thahn, thank you for the Response. I did add all the References
![Screenshot (174)](https://user-images.githubusercontent.com/9866193/151198104-05486f5b-a444-4b12-92b1-0de4cb0e53d4.png)
.

**Comment by Noath2302** [comment]
I have checked your code,
![image](https://user-images.githubusercontent.com/29188162/151200686-621349ab-7f54-4f32-ac9e-69d954f3d247.png)
 
In case you have added the reference project, changing the Target Framework to .NET 6 works.
The issue was that because you used .NET 5, your Program.cs must have the main function inside, which was changed in .NET 6.
There was also some syntax error on the code you upload too, please fix it.
You can either:
- add a Main function and stick to .NET 5,
- change the Framework to .NET 6
- make a UnitTest Project MSTest which is the same for both version
